# Generated by Django 5.0.6 on 2026-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='username',
        ),
        migrations.AddField(
            model_name='examsession',
            name='name',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
