# Generated by Django 5.0.6 on 2026-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0002_remove_examsession_username_examsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
