# Generated by Django 5.0.6 on 2026-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0003_examsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
