# Generated by Django 5.0.6 on 2026-03-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='department',
            field=models.TextField(null=True),
        ),
    ]
