# Generated by Django 5.0.6 on 2026-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0005_alter_examsession_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
