# Generated by Django 5.0.6 on 2026-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0006_alter_examsession_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
