# Generated by Django 5.0.6 on 2026-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coding', '0007_alter_examsession_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AddField(
            model_name='submission',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
